# Generated by Django 5.0 on 2023-12-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
