# Generated by Django 5.0 on 2023-12-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
