# Generated by Django 5.0 on 2024-01-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('Academic questions', 'Academic questions'), ('Courses', 'Courses'), ('Registration', 'Registration'), ('Events', 'Events')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
