# Generated by Django 5.0 on 2024-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_category_remove_thread_forum_thread_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
