# Generated by Django 5.0 on 2024-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
